"""
This script performs a quality audit on the "Generation" phase of the RAG system. 
It uses an "LLM-as-a-Judge" approach to evaluate how well the chatbot generates 
medical answers based on retrieved context.

KEY WORKFLOW:
1. Load a set of test questions from a .jsonl evaluation file.
2. Run each question through the live RAG pipeline (get_bot_response).
3. Send the generated answer and the source context to a high-capability LLM 
   (the Judge) to score Groundedness and Relevance (1-5).
4. Verify if the system correctly refused to answer unsafe/out-of-scope questions.
5. Export a detailed CSV report used by the Generation Dashboard.

HOW TO RUN:
Ensure your environment variables (API keys) are set and you are in the project root.
Execute using:
    python -m scripts.evaluate_generation
================================================================================
"""
import json
import time
import csv
import sys
import re  
from pathlib import Path

# --- SYSTEM PATH CONFIGURATION ---
# Ensure the root directory is in sys.path so 'src' and 'app' modules are importable
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.system import get_bot_response
from src.api import call_uc3m_api
from src.constants import DEFAULT_K, DEFAULT_THRESHOLD 

# --- EVALUATION PROMPTS ---

def get_evaluator_prompt(question, context, answer):
    """
    Generates a structured prompt for the LLM Auditor.
    
    The prompt instructs the judge to compare the 'Generated Answer' against the 
    'Clinical Context' to ensure no hallucinations occurred (Groundedness) and 
    that the user's specific query was addressed (Relevance).

    Args:
        question (str): The original user query.
        context (str): The raw text chunks retrieved from the vector DB.
        answer (str): The response generated by the RAG bot.
    """
    return f"""
    You are a Medical Quality Auditor for a RAG system. 
    Evaluate the following answer based on the provided clinical context.

    ### Question: {question}
    ### Context: {context}
    ### Generated Answer: {answer}

    Provide a score from 1 to 5 for:
    1. GROUNDEDNESS: Is the answer fully supported by the context? (1=Hallucination, 5=Perfectly Grounded)
    2. RELEVANCE: Does it answer the user's question? (1=Irrelevant, 5=Perfectly Relevant)

    Format your response EXACTLY like this:
    Groundedness: [score]
    Relevance: [score]
    Reasoning: [one sentence explanation]
    """

# --- CORE EVALUATION LOGIC ---

def run_gen_eval(eval_set_path, output_path):
    """
    Orchestrates the evaluation pipeline for an entire dataset.

    Args:
        eval_set_path (str): Path to the .jsonl file containing test questions.
        output_path (str): Path where the final .csv results will be saved.
    """
    # Load models/index (imports inside function to prevent loading if not executed)
    from app import load_rag_system
    model, reranker, index, chunks = load_rag_system()

    # Load test questions from JSONL
    with open(eval_set_path, 'r', encoding='utf-8') as f:
        questions = [json.loads(line) for line in f]

    results = []
    
    for q in questions:
        print(f"Evaluating {q['id']}...")
        start_t = time.time()
        
        # 1. GENERATION PHASE: Run the actual RAG pipeline
        # This uses the optimal 'k' and 'threshold' defined in constants.py
        answer, retrieved, quality = get_bot_response(
            q['question'], model, reranker, index, chunks, 
            top_k=DEFAULT_K, 
            threshold=DEFAULT_THRESHOLD
        )
        latency = time.time() - start_t

        # 2. SAFETY CHECK: Verify if the system refused to answer
        # Standard refusal prefix is checked to determine if the bot "stayed silent"
        is_refusal = "I'm sorry, I don't have enough information" in answer
        refusal_ok = (is_refusal == q['expected_refusal'])

        # 3. AUDIT PHASE: LLM-as-a-Judge
        g_score, r_score, reason = 0, 0, "Refusal Case"
        
        # We only judge quality if the bot actually provided an answer
        if not is_refusal and retrieved:
            context_text = "\n".join([c['content'] for c in retrieved])
            # Call the LLM API to act as the auditor
            eval_resp = call_uc3m_api(get_evaluator_prompt(q['question'], context_text, answer))
            
            # --- OUTPUT PARSING ---
            # Flexible regex parsing to extract the 1-5 scores from the judge's text response
            try:
                g_match = re.search(r"Groundedness:\s*(\d)", eval_resp, re.IGNORECASE)
                r_match = re.search(r"Relevance:\s*(\d)", eval_resp, re.IGNORECASE)
                reason_match = re.search(r"Reasoning:\s*(.*)", eval_resp, re.IGNORECASE)

                g_score = int(g_match.group(1)) if g_match else 0
                r_score = int(r_match.group(1)) if r_match else 0
                reason = reason_match.group(1).strip() if reason_match else eval_resp.strip().replace("\n", " ")
                
                # Flag cases where the judge didn't provide a clear numerical score
                if g_score == 0 or r_score == 0:
                    reason = f"Parsing Warning: Could not find scores in: {eval_resp[:50]}..."
            except Exception as e:
                reason = f"Parsing Error: {str(e)}"

        # 4. RECORD KEEPING: Prepare row for CSV export
        results.append({
            "id": q['id'],
            "question": q['question'],
            "language": q.get('language', 'en'), # Added for dashboard_gen.py
            "expected_refusal": q['expected_refusal'],
            "actual_refusal": is_refusal,
            "refusal_correct": refusal_ok,
            "groundedness": g_score,
            "relevance": r_score,
            "latency": round(latency, 2),
            "reasoning": reason
        })

    # --- EXPORT TO CSV ---
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_file, 'w', newline='', encoding='utf-8') as f:
        if results:
            writer = csv.DictWriter(f, fieldnames=results[0].keys())
            writer.writeheader()
            writer.writerows(results)
    
    print(f"Evaluation complete. Results saved to {output_path}")

# --- ENTRY POINT ---
if __name__ == "__main__":
    run_gen_eval("evaluation/dailymed_eval_v2.jsonl", "evaluation/generation_results.csv")