"""
This script provides a standardized interface to interact with the UC3M API
infrastructure. It is responsible for sending prompts to the LLM (specifically 
Llama 3.1:8b) and retrieving the generated text. 

It manages:
1. Environment Variable Loading: Securely retrieves API keys.
2. Security Configuration: Handles specific SSL/TLS certificate requirements 
   for the UC3M network environment.
3. Network Requests: Manages the POST payload, timeouts, and error handling 
   for the remote server connection.

HOW TO RUN:
This script is a utility module and is not intended to be run standalone. 
It is imported by other scripts (like system.py or evaluate_generation.py).
To test connectivity, ensure your .env file contains:
    UC3M_API_KEY=your_key_here
================================================================================
"""
from __future__ import annotations

import os
import requests
import urllib3
from dotenv import load_dotenv

# --- CONFIGURATION ---

# Load environment variables from the .env file located in the project root.
# This ensures that the UC3M_API_KEY is available to the script without 
# hardcoding sensitive credentials in the source code.
load_dotenv()

# Disable InsecureRequestWarning because 'verify=False' is used in the 
# requests call to accommodate the UC3M internal certificate environment.
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def call_uc3m_api(prompt: str, model_name: str = "llama3.1:8b") -> str:
    """
    Sends a text prompt to the UC3M API and returns the generated response.

    Args:
        prompt (str): The text instruction or context to be processed by the LLM.
        model_name (str): The specific model identifier. Defaults to "llama3.1:8b", 
                         which is the primary model for this project.

    Returns:
        str: The text response generated by the LLM, or a descriptive error message 
             if the connection or authentication fails.
    """
    # The endpoint URL for the UC3M generative API
    api_url = "https://yiyuan.tsc.uc3m.es/api/generate"
    
    # Retrieve the API key loaded from the .env file
    api_key = os.environ.get("UC3M_API_KEY")
    
    # Validation: Ensure the system has an identity before attempting a request
    if not api_key:
        return "Error: UC3M_API_KEY is not set. Please check your .env file."

    # Standard header for API Key authentication
    headers = {"X-API-KEY": api_key}
    # The JSON payload structure required by the UC3M 'generate' endpoint
    # 'stream': False ensures we wait for the full response before returning
    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False,
    }

    try:
        # POST Request Execution:
        # - verify=False: Skips SSL certificate validation (required for this specific environment)
        # - timeout=120: Allows up to 2 minutes for the LLM to process complex clinical prompts
        response = requests.post(api_url, headers=headers, json=payload, verify=False, timeout=120)
        # Raise an exception for HTTP error codes (e.g., 401 Unauthorized, 500 Server Error)
        response.raise_for_status()
        # Extract and return the content from the 'response' field of the JSON result
        return response.json().get("response", "Error: No response field.")
    except Exception as e:
        # Catch-all for network issues, timeouts, or API-side failures
        return f"API connection failed: {str(e)}"