"""
src/constants.py
----------------
Central configuration file for the DailyMed NLP pipeline.
Standardizes LOINC codes, groups them into semantic Super-Groups, 
and defines token-based chunking constraints.
"""

# --- MASTER LOINC MAPPING ---
# Maps specific medical codes to clean, human-readable categories.
MASTER_LOINC_MAP = {
    # Core Clinical Safety & Usage
    "34066-1": "BOXED_WARNING",
    "34067-9": "INDICATIONS_AND_USAGE",
    "34068-7": "DOSAGE_AND_ADMINISTRATION",
    "34070-3": "CONTRAINDICATIONS",
    "34071-1": "WARNINGS",
    "43685-7": "WARNINGS_AND_PRECAUTIONS",
    "34084-4": "ADVERSE_REACTIONS",
    "34088-5": "OVERDOSAGE",
    "42232-9": "PRECAUTIONS",

    # Specific Populations
    "42228-7": "PREGNANCY",
    "34077-8": "PREGNANCY_TERATOGENIC",
    "34078-6": "PREGNANCY_NON_TERATOGENIC",
    "34079-4": "LABOR_AND_DELIVERY",
    "34080-2": "NURSING_MOTHERS",
    "77290-5": "LACTATION",
    "34081-0": "PEDIATRIC_USE",
    "34082-8": "GERIATRIC_USE",
    "77291-3": "REPRODUCTIVE_POTENTIAL",
    "43684-0": "SPECIFIC_POPULATIONS",
    "88828-9": "RENAL_IMPAIRMENT",
    "88829-7": "HEPATIC_IMPAIRMENT",

    # Clinical Science & Pharmacology
    "34073-7": "DRUG_INTERACTIONS",
    "34074-5": "LAB_TEST_INTERACTIONS",
    "34075-2": "LABORATORY_TESTS",
    "34090-1": "CLINICAL_PHARMACOLOGY",
    "43679-0": "MECHANISM_OF_ACTION",
    "43681-6": "PHARMACODYNAMICS",
    "43682-4": "PHARMACOKINETICS",
    "34092-7": "CLINICAL_STUDIES",
    "90374-0": "CLINICAL_TRIALS_EXPERIENCE",
    "90375-7": "POSTMARKETING_EXPERIENCE",
    "49489-8": "MICROBIOLOGY",
    "34083-6": "NONCLINICAL_TOXICOLOGY",
    "34091-9": "ANIMAL_TOXICOLOGY",
    "66106-6": "PHARMACOGENOMICS",
    "88830-5": "IMMUNOGENICITY",

    # Product Logistics & Ingredients
    "34089-3": "DESCRIPTION",
    "43678-2": "DOSAGE_FORMS_STRENGTHS",
    "34069-5": "HOW_SUPPLIED_STORAGE",
    "44425-7": "STORAGE_HANDLING",
    "51727-6": "INACTIVE_INGREDIENTS",
    "43683-2": "RECENT_MAJOR_CHANGES",
    "60558-4": "HANDLING_AND_STERILIZATION",
    "48780-1": "PRODUCT_DATA_LISTING",
    "51945-4": "PACKAGE_LABEL_TEXT",
    "48779-3": "TABLE_OF_CONTENTS",

    # Patient-Facing
    "34076-0": "PATIENT_COUNSELING_INFO",
    "42231-1": "MEDGUIDE_SECTION",
    "42230-3": "PATIENT_PACKAGE_INSERT",
    "68498-5": "PATIENT_MED_INFO",
    "38056-8": "SUPPLEMENTAL_PATIENT_MATERIAL",
    "82598-4": "REMS_MEDICATION_GUIDE",
    "88436-1": "PATIENT_COUNSELING_TEXT",

    # OTC & Abuse
    "42227-9": "DRUG_ABUSE_DEPENDENCE",
    "34085-1": "CONTROLLED_SUBSTANCE",
    "34086-9": "ABUSE",
    "34087-7": "DEPENDENCE",
    "55106-9": "OTC_ACTIVE_INGREDIENT",
    "55105-1": "OTC_PURPOSE",

    # Catch-All
    "42229-5": "UNCLASSIFIED",
    "None": "OTHER"
}

# --- SUPER GROUP MAPPING ---
# Consolidates the above categories into 6 Semantic Super-Groups.
# This is used by the Dynamic Accumulator to group related sections.
SUPER_GROUP_MAP = {
    # Group: SAFETY_AND_RISK
    "BOXED_WARNING": "SAFETY_RISK",
    "WARNINGS": "SAFETY_RISK",
    "WARNINGS_AND_PRECAUTIONS": "SAFETY_RISK",
    "CONTRAINDICATIONS": "SAFETY_RISK",
    "PRECAUTIONS": "SAFETY_RISK",
    "DRUG_ABUSE_DEPENDENCE": "SAFETY_RISK",
    "CONTROLLED_SUBSTANCE": "SAFETY_RISK",
    "ABUSE": "SAFETY_RISK",
    "DEPENDENCE": "SAFETY_RISK",

    # Group: CLINICAL_USAGE
    "INDICATIONS_AND_USAGE": "USAGE_CLINICAL",
    "DOSAGE_AND_ADMINISTRATION": "USAGE_CLINICAL",
    "DOSAGE_FORMS_STRENGTHS": "USAGE_CLINICAL",
    "OTC_ACTIVE_INGREDIENT": "USAGE_CLINICAL",
    "OTC_PURPOSE": "USAGE_CLINICAL",

    # Group: ADVERSE_EVENTS
    "ADVERSE_REACTIONS": "ADVERSE_INTERACTIONS",
    "DRUG_INTERACTIONS": "ADVERSE_INTERACTIONS",
    "LAB_TEST_INTERACTIONS": "ADVERSE_INTERACTIONS",
    "OVERDOSAGE": "ADVERSE_INTERACTIONS",
    "POSTMARKETING_EXPERIENCE": "ADVERSE_INTERACTIONS",
    "LABORATORY_TESTS": "ADVERSE_INTERACTIONS",

    # Group: SPECIAL_POPULATIONS
    "PREGNANCY": "SPECIAL_POPULATIONS",
    "PREGNANCY_TERATOGENIC": "SPECIAL_POPULATIONS",
    "PREGNANCY_NON_TERATOGENIC": "SPECIAL_POPULATIONS",
    "NURSING_MOTHERS": "SPECIAL_POPULATIONS",
    "PEDIATRIC_USE": "SPECIAL_POPULATIONS",
    "GERIATRIC_USE": "SPECIAL_POPULATIONS",
    "LACTATION": "SPECIAL_POPULATIONS",
    "SPECIFIC_POPULATIONS": "SPECIAL_POPULATIONS",
    "LABOR_AND_DELIVERY": "SPECIAL_POPULATIONS",
    "REPRODUCTIVE_POTENTIAL": "SPECIAL_POPULATIONS",
    "RENAL_IMPAIRMENT": "SPECIAL_POPULATIONS",
    "HEPATIC_IMPAIRMENT": "SPECIAL_POPULATIONS",

    # Group: PHARMACOLOGY_SCIENCE
    "CLINICAL_PHARMACOLOGY": "PHARMACOLOGY",
    "MECHANISM_OF_ACTION": "PHARMACOLOGY",
    "PHARMACODYNAMICS": "PHARMACOLOGY",
    "PHARMACOKINETICS": "PHARMACOLOGY",
    "CLINICAL_STUDIES": "PHARMACOLOGY",
    "CLINICAL_TRIALS_EXPERIENCE": "PHARMACOLOGY",
    "NONCLINICAL_TOXICOLOGY": "PHARMACOLOGY",
    "ANIMAL_TOXICOLOGY": "PHARMACOLOGY",
    "MICROBIOLOGY": "PHARMACOLOGY",
    "PHARMACOGENOMICS": "PHARMACOLOGY",
    "IMMUNOGENICITY": "PHARMACOLOGY",

    # Group: PRODUCT_LOGISTICS
    "DESCRIPTION": "PRODUCT_LOGISTICS",
    "HOW_SUPPLIED_STORAGE": "PRODUCT_LOGISTICS",
    "STORAGE_HANDLING": "PRODUCT_LOGISTICS",
    "INACTIVE_INGREDIENTS": "PRODUCT_LOGISTICS",
    "PRODUCT_DATA_LISTING": "PRODUCT_LOGISTICS",
    "PACKAGE_LABEL_TEXT": "PRODUCT_LOGISTICS",
    "RECENT_MAJOR_CHANGES": "PRODUCT_LOGISTICS"
}

# --- OPTIMAL RETRIEVAL SETTINGS ---
# Based on grid_retrieval_comparison.csv analysis
DEFAULT_K = 8
DEFAULT_THRESHOLD = 0.60

# --- CHUNKING SETTINGS ---
# Optimized for all-mpnet-base-v2 (512 token window)
MAX_TOKEN_LENGTH = 480  
CHUNK_OVERLAP_TOKENS = 50

# High-priority groups to be analyzed first in the chatbot logic
HIGH_PRIORITY_GROUPS = [
    "SAFETY_RISK", 
    "USAGE_CLINICAL", 
    "ADVERSE_INTERACTIONS"
]